raw_emails = """
thebirdsanchez@gmail.com
tigo.grimborn@gmail.com
yazzieardin469@gmail.com
hugohenaine@gmail.com
caseynunn01@gmail.com
pajkersss@gmail.com
renanmaciel91@gmail.com
iskamdraiv@gmail.com
kahronoz1@gmail.com
ajsaady@gmail.com
gomadoufu9741@yahoo.co.jp
christophe.pereira.dom@hotmail.com
christianbanda348@gmail.com
lycaongray20@gmail.com
gonzalokai306@gmail.com
merrymia@gmx.com
wasan7899@gmail.com
bosshoodrat@gmail.com
lewistashawn0602@gmail.com
filt.noble@gmail.com
redrangerdrew@gmail.com
janbrkic52@gmail.com
p.carr2409@gmail.com
centralapartments36@gmail.com
r1ftgamez16@gmail.com
beartimebro@gmail.com
gustavomendez4571@gmail.com
ckennie95@gmail.com
kaper8069@gmail.com
ilyamarchenko1980@gmail.com
brunoaugusto.web@gmail.com
noahkite0@gmail.com
isotopcraft@googlemail.com
liegreto.2008@gmail.com
alexlove32@icloud.com
lucas7485192@gmail.com
satanfromsi@aol.com
rainbowpandamaya@gmail.com
poods455@gmail.com
moldujulie@gmail.com
matias23090907@gmail.com
hefnermd85@gmail.com
bjay691tommy@gmail.com
connorherrold4@gmail.com
jamestsung99@gmail.com
traviscantu5@gmail.com
kennljh27@hotmail.com
mrpyther@gmail.com
nnufe.twitch@gmail.com
gsptwitch67@gmail.com
erhendiltelvani@gmail.com
djoo@live.com
lelboy10@gmail.com
rruiz.esquer@gmail.com
warpred06@gmail.com
lyconadams@gmail.com
mikazuchireborn@gmail.com
lolpaskyra16@gmail.com
sharkmansam1111@gmail.com
xcuenta1.1@outlook.com
reecemooneyy@gmail.com
sergiobreyes2@gmail.com
anneauxnyme86@gmail.com
aaronsmith7@msn.com
crimson535353@gmail.com
takumixmisaki2018@gmail.com
kaiden70freeman@gmail.com
frank.grosso.playgames@gmail.com
saulgoodman8611@hotmail.com
blitzkreig02@yahoo.com
ecchinest69@gmail.com
ravagers281@gmail.com
korzkash915@gmail.com
kingsley.catenzaro.01@gmail.com
ccm.santiago823@gmail.com
cjmischel@gmail.com
amirunhaqim@gmail.com
riyadhjones100@gmail.com
dahooombab10@gmail.com
gilad998877@gmail.com
ggrieme47@gmail.com
towa.icloud@gmail.com
roseidan645@gmail.com
petekats3@gmail.com
thesealtamer@gmail.com
joseguerrero004@gmail.com
lisagg420@gmail.com
sourmonster231@proton.me
anione.me@pm.me
guka3621@gmail.com
ngga141414@gmail.com
2528239@proton.me
Wylie8921@gmail.com
GreedxGreedo@gmail.com
visionypasado@gmail.com
jackiesparrow138@gmail.com
bruhbrehbroo@gmail.com
s1mplyk@proton.me
mandon95@yahoo.com
tanjiroinval@gmail.com
sbaker12345mario@gmail.com
kev.ho@web.de
darreljeckain@gmail.com
monkeydtimtim@gmail.com
serlon9891@gmail.com
unleashednicole@gmail.com
nathanwatkins870@gmail.com
schlesserlucas4@gmail.com
aonicnevo@gmail.com
knockoff948@gmail.com
zydosdaun@gmail.com
cvstanfordgames1@gmail.com
axelayres69@gmail.com
t15480506@gmail.com
nikeendrit78@gmail.com
luizgumariano@gmail.com
jcm78710@gmail.com
codghost909@gmail.com
jannes0709@gmail.com
eathallyashfaaq20@gmail.com
betetalimo@gmail.com
clement40202@gmail.com
iformalgt@gmail.com
blaineketchum1@gmail.com
fernandojpr29b@gmail.com
tucker.anthony98@gmail.com
alindahl21@gmail.com
janbrkix@gmail.com
jdlan7883@gmail.com
stonkandsteal@gmail.com
bothaleigham@gmail.com
candymanspecial@gmail.com
oviedojorge56@gmail.com
penater12@gmail.com
oosterbeekstefan7@gmail.com
nhatnam140886@gmail.com
chupapimunyanyo562@gmail.com
rocketman1711@icloud.com
valthor31@gmail.com
gakizoai@gmail.com
genaro.poblano@gmail.com
medina22475@gmail.com
soggypancakes2034@gmail.com
paulsnake@live.com
sandreas81@yahoo.de
kev-du-73230@hotmail.fr
lxstcj420@gmail.com
craigmike666@gmail.com
janbrkic8@gmail.com
tafilkids@gmail.com
rtknowbetter@gmail.com
kuraiyui@gmail.com
flickerfly4@gmail.com
r6demonlord@gmail.com
darina198627@gmail.com
erikgonzaes336@gmail.com
maddenhh82@gmail.com
ilgiz.zheenbkov@gmail.com
benito.ugalde141@gmail.com
lancywancy30@gmail.com
adamgt30@gmail.com
pauliusprozz@gmail.com
clippe@live.com
nobody250.nobody250@gmail.com
jxztnover9000@gmail.com
rod1602iron@gmail.com
sqxrwrld@gmail.com
sixthneigh@gmail.com
wrldsqxr@gmail.com
matureidiot@gmail.com
mazen.ounais@gmail.com
aahaalmarzouqi@gmail.com
ted4503@gmail.com
anhad.khehra85@gmail.com
grandtheftbeast@gmail.com
parquerezekie@gmail.com
paddde92@gmail.com
loeylosch@gmail.com
ackermann.marcus91@gmail.com
stephen.j.feltham@gmail.com
ecasafi@gmail.com
jacobdylanterre@gmail.com
timsspams@web.de
hitmankill777@hotmail.com
ttvsaeko@gmail.com
adamthompson282828@gmail.com
serenelyrei@gmail.com
cruzalbertoaguilar97@gmail.com
zorro1214b@gmail.com
w61061516@gmail.com
bananaslaps32@gmail.com
namieanims@gmail.com
cafc127@gmail.com
beagle-apurarse0i@icloud.com
k.mirobi@gmail.com
l3o5amuels@gmail.com
edpw635@gmail.com
remingtonharbaugh@gmail.com
sebastianuseryt@gmail.com
steveurkle011@gmail.com
pedro722moita@gmail.com
cowenarme@yahoo.com
joenut846@gmail.com
tylerbutler1016@gmail.com
martin.janota2003@gmail.com
logan.bedisjj86@gmail.com
ahnafamiral@gmail.com
chavezw380@gmail.com
faisaloofg@gmail.com
hootun139@gmail.com
reventoncoupe@gmail.com
firedragon1251@gmail.com
aguerra3104@gmail.com
peyongo.zeledon@gmail.com
camaroncolemon09@gmail.com
askthebikeman781@gmail.com
frost719@hotmail.com
unknownuserrequest3@gmail.com
diegofernandezroman1@gmail.com
llll17.66llll@gmail.com
kirchersamuel24@gmail.com
aukrkfffd@gmail.com
vargisan@gmail.com
vargisan4@gmail.com
Manwitnolegs@gmail.com
jack.paulage7@gmail.com
ronaldfedrigo15@gmail.com
ragnarokx.x008@gmail.com
proczy117@gmail.com
duck91647@gmail.com
sueiken9@gmail.com
limocoder@gmail.com
dombeach157@gmail.com
hikaru1826@mail.ru
christopherreyes1006@gmail.com
charlesridderx113@gmail.com
xboxprojosh@gmail.com
harryjodrell642@gmail.com
finalgamevl@gmail.com
tobekoryx@gmail.com
pdpblackbird@gmail.com
jungongteng381@gmail.com
vonhans.fokker@gmail.com
jpfitzsimmons221019@gmail.com
camel23@web.de
infinydark@gmail.com
kingof8verything@gmail.com
sebastian.rauch1234@gmail.com
imackenzie349@gmail.com
djoo.au@gmail.com
lordsirders@gmail.com
yovannburel@gmail.com
challopenjo@gmail.com
jp819062@gmail.com
tjnoodle88@gmail.com
leepeyton9@gmail.com
ipmdeluxe@gmail.com
jpugh.nevada@gmail.com
suckysuckymeme@gmail.com
alex-dempsey@hotmail.com
masterkevinyu@gmail.com
unone8246@gmail.com
greenlandsucks@gmail.com
ashthefreezer@gmail.com
bombt73@gmail.com
iddiifwiw@gmail.com
jtlewis666@gmail.com
ndisso553@gmail.com
owen1234@email.com
esdrasreis559@gmail.com
silvrr23@gmail.com
tiberiupopescu18@gmail.com
iamyoungwilliamsii@gmail.com
overfiendai@gmail.com
warriordark393@gmail.com
cnotepb12@gmail.com
creel-fesses9w@icloud.com
anione.headphone412@passmail.net
leodamn9@gmail.com
mateolongobardi10@gmail.com
randomizer6306@gmail.com
jracephoenix@gmail.com
td10028@gmail.com
fatpoon903@gmail.com
bigboybobbygg@gmail.com
salemmilo02@gmail.com
fathercattus@gmail.com
seranaai888@gmail.com
kaosphoenix2010@gmail.com
marshalldewetter1031@gmail.com
mmorales7391@gmail.com
appletoss3@gmail.com
hustonwright7@gmail.com
gabewinchester07@outlook.com
morane.kevin@gmail.com
bugleriskyle@gmail.com
matthewweinre@gmail.com
kimberlyyasminthiele@gmail.com
btjobbitt@gmail.com
mainy.central@gmail.com
r34lbillcosby@gmail.com
akalinowski555@gmail.com
zekeodon@gmail.com
zilchodonnell@gmail.com
chouchou1412310@gmail.com
leerisner1864@gmail.com
mihoyogibmefreeprimo176@gmail.com
mattmillwood89@gmail.com
hdisjskshshsis@gmail.com
engine17lex@gmail.com
thzedefcon@gmail.com
shanks.10qp@gmail.com
oltmannsbob200@gmail.com
ytfen.zitro@gmail.com
jay674737@gmail.com
smithjason839@gmail.com
patreonuse37@gmail.com
jamessun90@gmail.com
mionhialn@gmail.com
gloster.staffunder17@gmail.com
lightfootbrent1@gmail.com
leoncloud88@gmail.com
carleovi24@gmail.com
jak.griffin95@gmail.com
nutbust188@gmail.com
weboughtazooyay@gmail.com
stormraijin69@gmail.com
jccurran@alaska.edu
blakebeckman420@gmail.com
howie0183@gmail.com
ajraleigh2016@gmail.com
cowenbarm@gmail.com
cutestcouplegw@gmail.com
jamieparkes2002@gmail.com
devontncampbell@gmail.com
joel_becerril31@yahoo.com
hunter.stonebreaker@gmail.com
hggabe15@gmail.com
wooby8005@gmail.com
waterbuffalo126@gmail.com
knas120501@gmail.com
eriv20133@gmail.com
yuukasugawara7@gmail.com
taylorowens110703@gmail.com
pokemasterlj3@gmail.com
goowhack647@gmail.com
lucascrane346@gmail.com
cbrace987@gmail.com
bradshawcorey1@gmail.com
franciscocarvalho097@gmail.com
skechers59@gmail.com
sooskid@gmail.com
joel.anderjaska@gmail.com
mitchgraham350@gmail.com
luke.beranek723@gmail.com
cf48483@gmail.com
zsullivan120@gmail.com
farooqt7466@gmail.com
kylefountain760@gmail.com
philproteau@icloud.com
crannywanny08@gmail.com
ashton.coleman@lowndesboe.org
isratos9919@gmail.com
djoo.89@gmail.com
fuzei6826@gmail.com
therelentless00@gmail.com
jacobmerenda@yahoo.com
spectrobesrock497@gmail.com
rimussabouet49@gmail.com
satsahebkabirdevkabhakt@gmail.com
ismende03@gmail.com
yourgoodboy93@gmail.com
tobiasgerald.kanner@gmail.com
kaynonpornhub@gmail.com
lolmeme2323@gmail.com
hehemi9105@exitbit.com
jstarksisaac@gmail.com
hotimustaf@outlook.de
facings_singe7g@icloud.com
Beckerkody777@gmail.com
vdw69max@gmail.com
ffleischmann03@gmail.com
phoenixboland88@gmail.com
nooranweer2007@gmail.com
gitgit142@gmail.com
manualbreathing1337@gmail.com
yenudazlhuym@gmail.com
baptistegarcia69500@gmail.com
donkeyape443@gmail.com
rahnchris707@googlemail.com
jaybasics062005@gmail.com
kanye364@gmail.com
kadebass16@gmail.com
oulberg925@gmail.com
hanzljan17@gmail.com
wiktorfiedorowicz124@gmail.com
aleferro886@gmail.com
accdee133455@gmail.com
mattyjt89@googlemail.com
jmankoopa@gmail.com
locoricankai@gmail.com
dannymashedpotates757@gmail.com
tag-grant-charred@duck.com
kennethsnider28@icloud.com
jerin4gs@gmail.com
jules.lh.letulzeau@gmail.com
tjswezey@yahoo.com
sebi120304@gmail.com
emre20380@icloud.com
Nightmarerhbestfan@hotmail.com
w.q1614@gmail.com
kjames4357@outlook.com
GoinCoastalAT@aol.com
bratsoto81@gmail.com
juansa0904@gmail.com
ethanseashols20007@gmail.com
pixardown@gmail.com
ferraricalifornia.simon7@gmail.com
jayanione05@gmail.com
toastlogos@gmail.com
markcrowl821@gmail.com
thomasatravis98@gmail.com
richardgibson1999@gmail.com
joel.b320@gmail.com
kevinobermueller562@gmail.com
mdk01272006@gmail.com
rswing2005@gmail.com
steamdrive13@gmail.com
slimmamba14@gmail.com
stanvierveijzer@gmail.com
merick1213@gmail.com
coopersharman@gmail.com
bobomcjoe@gmail.com
yufrontinme@hotmail.com
jacobmanzano08@gmail.com
luki88kr@gmail.com
nolskenny@gmail.com
bonk1221@gmail.com
vhozon74@gmail.com
santosvgold@gmail.com
angcelloxo@gmail.com
gxcbg2522@gmail.com
skyswim07@gmail.com
jacobhunt201401@gmail.com
moth3rrussiarussia32@gmail.com
yyoru.0919@gmail.com
xelighax@gmail.com
cotywr@gmail.com
thememeyway@gmail.com
rpolyle@gmail.com
pouyaroohandeh1@gmail.com
antunezlucio980@gmail.com
coxcamden03@gmail.com
giancarlosegebre242@gmail.com
progamer135246@gmail.com
ethanquach666@gmail.com
deancrook003@gmail.com
jayjrwalkerbackup@gmail.com
mmmillar99@gmail.com
jonathansilva229@gmail.com
kash.kw@gmail.com
jacksonschell28@gmail.com
cashmastercody7@gmail.com
kyle.kramer1@icloud.com
menasacres225@gmail.com
jurru005@gmail.com
tyler.m.wood01@gmail.com
declangoodwin04@gmail.com
justlucidgaming@gmail.com
allensmith757@gmail.com
icebleu99@gmail.com
jaywalkerbackup05@gmail.com
ctaustin91@gmail.com
ihamakijoona@gmail.com
senbonzakura.waifu.ai@gmail.com
roman-reimer@gmx.de
jrdavies1601@gmail.com
alistairinnes2005@gmail.com
macchan712o@gmail.com
mylanpalente@hotmail.fr
tommeat96@gmail.com
jay052054@gmail.com
evor092@gmail.com
farmville911@live.ca
mistart92@gmail.com
murilocatakuri@gmail.com
gonrazudai@gmail.com
j.skov2105@gmail.com
wannabe1627@gmail.com
jay062005basics@gmail.com
thefinalboss112@gmail.com
elkinbarron12345@gmail.com
hideya.0214@gmail.com
willgc13@gmail.com
intenzesquid@gmail.com
yengorgeousprincess@gmail.com
jaywalker062005backup@gmail.com
marleytiva@gmail.com
timothyleet09@gmail.com
josiahleehardin12@gmail.com
aeirowultx@gmail.com
seanr4903@gmail.com
nicnac2054@gmail.com
okorosimon200323@gmail.com
jkremers.jk11@gmail.com
hiyes7790@gmail.com
yeroviper@outlook.com
umuttur0@icloud.com
jay.jr.walker.061205@gmail.com
thomasclermont10@gmail.com
bonsai0516@gmail.com
rydeharry@gmail.com
kiritodoesthings@gmail.com
riotdogshitcompany19@gmail.com
nshnah17@gmail.com
yugobozzz@hotmail.de
fw190d14@gmail.com
drewstafford3@gmail.com
jmusic062005@gmail.com
spamman031@gmail.com
jayjrwalker2005@gmail.com
Jackdragonslayer48@gmail.com
nicholas@infinitycity.com
j82114809@gmail.com
Romanwarren04@Gmail.com
hot4bananas@gmail.com
mvnbcx@mail.com
edcastillo425@gmail.com
windmill415415@gmail.com
nvtdez@gmail.com
flooby57@googlemail.com
cbugg2021@outlook.com
micahritchie0117@gmail.com
arata.airi.arai.1012@gmail.com
adamjblyth@gmail.com
pharellbryan@gmail.com
califresh92@gmail.com
xaldinmarluxia@yahoo.de
jakepusey9999@gmail.com
sdeborn1@gmail.com
mav3rick925@gmail.com
loadingnowhere@gmail.com
jamesthebestguy@gmail.com
kmr4269@icloud.com
batuhan.r1asitoglu236@gmail.com
stormdadoggie@gmail.com
fd.sr.skds@gmail.com
jhvti321@gmail.com
jcfloreslira@gmail.com
riptidemgmt@gmail.com
mythheart1@gmail.com
genazsis20@gmail.com
kthowie@gmail.com
viktor.putnik1@gmail.com
cramos3920@gmail.com
ayu.0824@gmail.com
evdokimovserafim@gmail.com
haosandstylejc9101523@gmail.com
blueusnsean@gmail.com
hiroki.yasuba@gmail.com
gcw54025@gmail.com
hugoagomez2121@outlook.com
r.rampenthal97@gmail.com
jose.angel.sandoval.ll@gmail.com
christian45.cks@gmail.com
lostonlineooof@gmail.com
njpsybbiiywkss2@gmail.com
harryvirdee999@gmail.com
"""

formatted = ",\n".join([f"'{e.strip()}'" for e in raw_emails.strip().split("\n")])
print(formatted)
